const express = require("express");
const router = express.Router();

const middlewaresAuth = require("../middlewares/auth");
const authMiddlewares = new middlewaresAuth();
const controllerDeportista = require("../controllers/deportistas");
const deportistasController = new controllerDeportista();

const {
  imprimirDeudoresMesDeportistas,
} = require("../middlewares/generarPdf");

router.get(
  "/dashboard/deportistas/:disciplina",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.mostrarDeportistasPorDisciplina
);

router.get(
  "/dashboard/cargardeportista/:disciplina",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.mostrarCargaDeportista
);

router.get(
  "/dashboard/deportistas/:disciplina/pagos/:id",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.mostrarPagosDeportista
);

router.get(
  "/dashboard/deportistas/:disciplina/pagos/listadeudores/:fecha",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.listarDeudoresMesDeportistas
);

router.post(
  "/imprimirDeudoresMes/:disciplina",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  imprimirDeudoresMesDeportistas
);

router.post(
  "/cargarDeportista/:disciplina",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.cargarDeportista
);

router.delete(
  "/borrarDeportista/:id",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
  ],
  deportistasController.borrarDeportista
);

router.put(
  "/editarDeportista/:id",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
  ],
  deportistasController.editarDeportista
);

router.post(
  "/crearPagoDeportista",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
  ],
  deportistasController.crearPago
);

router.get(
  "/dashboard/editardeportista/:disciplina/:id",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
    authMiddlewares.verificarAccesoDisciplina("disciplina"),
  ],
  deportistasController.mostrarEdicionDeportista
);

router.get(
  "/getPagos/:id",
  [
    authMiddlewares.verificarSesion,
    authMiddlewares.verificarRol([
      "coordinador_futbol",
      "coordinador_tenis",
      "coordinador_voley",
      "coordinador_basquet",
      "coordinador_patin",
      "admin_futbol",
      "admin_tenis",
      "admin_voley",
      "admin_basquet",
      "admin_patin",
    ]),
  ],
  deportistasController.traerPagosPorDeportista
);

module.exports = router;
